### ISSUE TITLE
Typos in code examples at https://mjeanroy.github.io/junit-servers/tomcat/jupiter

### ISSUE THREAD

**Issue by mdfst13** [mjeanroy/junit-servers#24]
When I'm reading the documentation at https://mjeanroy.github.io/junit-servers/tomcat/jupiter there are several times where it says `EmbeddedTomcatConfiguration.build()` but it should say `EmbeddedTomcatConfiguration.builder()`.  It looks like `build` should only be called after `builder`.  

I'd have offered a pull request, but if that documentation is publicly editable somewhere, it is not obvious to me where.

**Comment by mdfst13** [comment]
My definition of publicly editable includes that I can go somewhere, edit, save the result on github (in this case), and then have it propagated back to the original.  So I would consider this publicly editable, albeit with approval required.  It just wasn't in a place that I would have naturally looked.  

Regardless of the semantics of publicly, you fixed it, so this issue can be closed.

**Comment by mjeanroy** [comment]
@mdfst13 Thank you. If you find other typos or if you think something is missing in the documentation, feel free to ropen an issue, or even better feel free to submit a pull request and I will be more than happy to merge it.
