### ISSUE TITLE
Tomcat / jetty not responding

### ISSUE THREAD

**Issue by nmwael** [mjeanroy/junit-servers#33]
Hi, I just tried your examples for jetty & tomcat, on junit 4 & 5..

When I put at breakpoint in, and goto a browser to see if an application responds, I can just wait for ever.. In my case I will have multiple applications deployed, some 3rd party and some internal.. What could be wrong?

os is windows 7

**Comment by nmwael** [comment]
could be a problem on my machine, just startet a normal jetty programaticly it does not respond either:(

**Comment by mjeanroy** [comment]
Hi @nmwael,
Would you be able to send me a small project where I can reproduce the issue?
