### ISSUE TITLE
Default webapp path causes Tomcat to emit warning

### ISSUE THREAD

**Issue by lfielke** [mjeanroy/junit-servers#455]
Using junit-servers-tomcat 2.1.0 in the default configuration, Tomcat emits a warning to the console:

```
WARNING: A context path must either be an empty string or start with a '/' and do not end with a '/'. The path [/] does not meet these criteria and has been changed to []
```

It would be nice if the default configuration didn't cause warnings to be emitted.

I can see that the EmbeddedTomcat class deploys the webapp to the path from the `configuration.getPath()`. By default the configuration sets this to `/` (com.github.mjeanroy.junit.servers.servers.AbstractConfiguration#DEFAULT_PATH), as printed in the warning message.

An easy workaround is to call `.withPath("")` on the `EmbeddedTomcatConfiguration` builder. This avoids the warning being emitted and things that use the path to build URLs seem to handle this case.

**Comment by mjeanroy** [comment]
Hi @lfielke,
It's fixed in version 2.1.1, thanks for the report!
