### ISSUE TITLE
Missing release notes

### ISSUE THREAD

**Issue by sfragata** [mjeanroy/junit-servers#5]
Hi, you have a great tool.
We use your project and I've seen there was an version update but there is no release notes.

We used 0.4.2 and I don't know what was changed for 0.5

**Comment by mjeanroy** [comment]
Hi, you're right, I added a [https://github.com/mjeanroy/junit-servers/blob/master/CHANGELOG.md](changelog file). Do you need more information? For the next release, the generation of this changelog will be automatic, that way I will not forget anything ;)

Thanks for your feedback!

**Comment by sfragata** [comment]
awesome, thats the information I need
Thanks
