### ISSUE TITLE
EmbeddedTomcat.createContext is now private in 0.6.0 (was protected)

### ISSUE THREAD

**Issue by PatrickTremblay** [mjeanroy/junit-servers#7]
Hello there,

I tried to upgrade to the release 0.6.0 and I noticed the method EmbeddedTomcat.createContext pass from protected to private so is no longer overridable. The comment on method still says "May be override by subclasses" so I'm guessing maybe it is a mistake.

Thank you,

ptremblay

**Comment by mjeanroy** [comment]
@PatrickTremblay I changed the visibility because I think it could led to weird bug if this method was overridden (but I forgot to update remove that comment).

Why do you need to override this method? I'm ok to release a new version to revert this change but maybe you need a feature that can be added in the core instead?

**Comment by PatrickTremblay** [comment]
Hi thank you for the quick response.

Since it was intentional, this is not a bug. I will evaluate with my team why we need to override this method and maybe create a feature request if need be. 

I will stick with version 0.5.0 for now and close this issue.

**Comment by mjeanroy** [comment]
> I will stick with version 0.5.0 for now and close this issue.

I fixed a lot of things in 0.6.0, so, as I said, I'm ok to release a 0.6.1 if you need to (just let me know by re-opening the issue).

**Comment by PatrickTremblay** [comment]
Perfect thank you.

**Comment by mjeanroy** [comment]
@PatrickTremblay Sorry for the delay, the version 0.6.1 should be available on maven central. In this version, the `createContext` method is now `protected`.

This method has also been deprecated, as I think it should be private, if it's a problem for you, please let me know (feel free to reopen the issue), I will be happy to discuss it!
