### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by rlubke** [mjeanroy/junit-servers#712]
I last reviewed this project about 4 months ago and had written some code to leverage the project.  I've had reason to return and followed the documentation link and was surprised to be redirected to, what appears to be, a German language blog entry on the project.  I seem to recall proper documentation with all of the attributes of the annotations and various usage examples.   Am I mis-remembering?  If not, is it possible to restore that older docs?

**Comment by mjeanroy** [comment]
Hi @rlubke,

Thanks for your message.

Looks like my domain name subscription expired a few weeks earlier, I did not notice, and someone bought it, re-used my own content (translated in German) 😔

Not sure what I can do legally, to be honest I don't have the time and the money to do something 🥹

In the meantime, I'll just buy another domain, there's nothing I can do in the short term...

**Comment by mjeanroy** [comment]
I removed the custom domain name in GitHub for now, you can access the doc here: https://mjeanroy.github.io/junit-servers/jetty/configuration

I noticed the doc might not be super up to date, please tell me if you see something wrong and I'll quickly fix it.

I plan to update the whole doc soon, but I'm a bit busy these days so I can't promise it will be done quickly.

**Comment by mjeanroy** [comment]
Closing, as I bought a new domain, and updated the DNS config, it should be good now.
